### ISSUE TITLE
No and this is not an issue about the rom.

### ISSUE THREAD

**Issue by m4w0lf** [DeadSquirrel01/lineage-16_a5_releases#10]
Hi,
yes I know it's not an issue of the rom, but is the only place i can ask you a question. Can kindly share your roomservice.xml for this version? It's a 2 seconds operation and I think anyone using your repo will appreciate it.
Thank you for your patience and consideration.
BR

**Comment by DeadSquirrel01** [comment]
https://pastebin.com/sA0H4W5H
here it is, those repos plus mines, but since i haven't uploaded a5-common for lineage >=15.0 i see it hard for you to compile it without porting that repo.
Anyway, I'm done here.
*Closing*, please don't reopen since this is an off-topic thing that has nothing to do with my releases (and it's not an issue as well)

**Comment by krmax44** [comment]
Can you please upload everything needed for building this ROM? Bugs can be fixed faster by many people, also open source is in the nature of Lineage OS.

**Comment by m4w0lf** [comment]
Just a little question: if you don't want anyone to be able to compile lineage using your release/porting/code, can you explain me why did you put your code on a public github repo? I do not have any problem with a choice like that, but it's about 2 months I'm trying to compile lineage with your repo, failing all times. Every time I belived I was doing something wrong. Only today I can claim it's not my setup fault and so I can definitevely use other ways.
