### ISSUE TITLE
Dial apk is way too loud

### ISSUE THREAD

**Issue by sebzieja** [DeadSquirrel01/lineage-16_a5_releases#16]
Dialer apk minimal volume is way too loud. Is there some way to decrease it even more?

When I call to someone throught messenger volume level is ok.

**Comment by sebzieja** [comment]
If someone has the same problem, this solves problem:
[mixer_paths_fix.zip](https://github.com/DeadSquirrel01/lineage-16_a5_releases/files/2708795/mixer_paths_fix.zip)

**Comment by DeadSquirrel01** [comment]
The mixer_paths in each release is taken from A5 stock rom, since we are using stock audio HAL (newer releases, so, 5th and up will have source built audio+tfa9895 amplifier hal, though). Now, i cant make thousands of mixer_paths for each person that downloads the rom just because they find audio too low/high.
Therefore, i'll close this "issue"

**Comment by sebzieja** [comment]
Yep, but changing values also fix echo when dialing someone. There is definitely some differences with stock rom.

**Comment by Brignoud** [comment]
If so, please reconsider that
But, I also understand, if we are very few to complain this it's understable the point of view to not work on this

**Comment by DeadSquirrel01** [comment]
Changing mixer_paths values dont fix echo
