### ISSUE TITLE
NFS is not supported

### ISSUE THREAD

**Issue by virtuacool** [DeadSquirrel01/lineage-16_a5_releases#23]
The ROM is spectacular and very stable!
Thank you so much for your work!
Revitalized my SM-500FU!
It's unfortunate not to have NFS support, which in my city is heavily used in public transport and payments in stores.
With NFS supported the ROM would be perfect !!!!
Once again, thank you!

**Comment by DeadSquirrel01** [comment]
If you meant "NFC", lineage doesn't support our nfc chip since 14.1. It's already stated in readme that it doesnt

**Comment by jplitza** [comment]
@DeadSquirrel01 I was able to somehow fix NFC in your 14.1 build (mainly by replacing `vendor/samsung/a5-common/proprietary/lib/hw/nfc_nci.msm8916.so`, I think, but [I also made some other changes](https://github.com/jplitza/android_device_samsung_a5-common/commits/cm-14.1)), so maybe it's not impossible to fix it? Or are you saying it still was supported in 14.1 but not afterwards, because something in LOS core changed?
