### ISSUE TITLE
Slugish recent apps screen

### ISSUE THREAD

**Issue by krmax44** [DeadSquirrel01/lineage-16_a5_releases#9]
The task manager is really slow, pressing the task manager button twice too fast results in no action (instead of switching to the last app).

Might be a Lineage related issue.

**Comment by DeadSquirrel01** [comment]
Double press menu button isn't a "sort of unique button" to switch to last app but you're making the system, first to switch to recent apps tab and then, to open last app. So, that's why it might be slower, especially if you have a lot of crap on your phone that slows down the system.
Reopen the issue if you have something else to say about this

**Comment by krmax44** [comment]
Even just tapping the recent apps button once with it the freshly installed ROM takes quite some time for the screen to show up, even with just one more background app. Same with pressing the home button or opening apps.
